feat: add reduce-multi-blank-lines option
metwork-framework/envtpl pull request #13
Opened 2019-05-27 12:51 UTC by thebaptiste

close: #11

2019-05-27 12:55 UTC, thefab requested changes
maybe you could add a test about this new feature ?

2019-05-27 15:41 UTC, thebaptiste commented
Changes done (2 tests added with and without new option)

2019-05-28 06:50 UTC, thefab approved these changes

2019-05-28 06:50 UTC, merged

2019-05-28 06:51 UTC, thefab commented
great ! don't forget to update the envtpl reference in mfext to get the new version and start to use it ;-)